image:
  repository: brandawg93/peanut
  tag: 2.6.1@sha256:044a11611b526f210306fc821b98975f050a1e35929fd4a9c8cce41bb736919b
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10688
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NUT_HOST: "localhost"
            NUT_PORT: 3493
            USERNAME: ""
            PASSWORD: ""
            WEB_PORT: "{{ .Values.service.main.ports.main.port }}"
