image:
  pullPolicy: IfNotPresent
  repository: ich777/quake3
  tag: latest@sha256:4ad762c0aab5e44703842c8131e7293592ee91e4d10f884c759a4fc68570adc3
persistence:
  serverfiles:
    enabled: true
    mountPath: /quake3
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 27960
        protocol: udp
        targetPort: 27960
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DL_URL_PATCH: https://ftp.gwdg.de/pub/misc/ftp.idsoftware.com/idstuff/quake3/quake3-1.32c.zip
            DL_URL_PR: https://ftp.gwdg.de/pub/misc/ftp.idsoftware.com/idstuff/quake3/linux/linuxq3apoint-1.32b-3.x86.run
            GAME_PARAMS: +set sv_punkbuster 0 +set fs_game osp +set com_hunkMegs 32
            Q3_MAP: q3dm1
            Q3_PORT: "27960"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
