image:
  pullPolicy: IfNotPresent
  repository: miniflux/miniflux
  tag: 2.1.4@sha256:e4fe75639f41e184668c33b0aec12ba0e3e740fedf9cc89a91d7a1ab43c2f5f4
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
cnpg:
  main:
    enabled: true
    database: miniflux
    user: miniflux
service:
  main:
    ports:
      main:
        port: 10091
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CREATE_ADMIN: 1
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
            RUN_MIGRATIONS: 1
            ADMIN_PASSWORD: changeme
            ADMIN_USERNAME: admin
          probes:
            liveness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 3
                httpGet:
                  path: /healthcheck
                  port: 8080
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 1
