image:
  pullPolicy: IfNotPresent
  repository: testdasi/simple-dns-doh
  tag: latest@sha256:b00ddf0edcd257640516150e1ada3525e36ec81de6e89f14af88e05baf50c8fe
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  dnsudp:
    enabled: true
    ports:
      dnsudp:
        enabled: true
        port: 53
        protocol: udp
        targetPort: 53
  main:
    ports:
      main:
        port: 53
        protocol: tcp
        targetPort: 53
