image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/recyclarr/recyclarr
  tag: 7.2.1@sha256:c293cc988c5123899ed4d42b31f227b986d36357688106effdb44e83a3bb9f5a
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      initContainers:
        initconfig:
          type: install
          enabled: true
          imageSelector: "image"
          command:
            - recyclarr
            - config
            - create
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            CRON_SCHEDULE: "@daily"
persistence:
  config:
    enabled: true
    mountPath: /config
    targetSelectAll: true
portal:
  open:
    enabled: false
