image:
  repository: yourselfhosted/slash
  pullPolicy: IfNotPresent
  tag: 1.0.0@sha256:5681d320acaabbe16dc0c03a254f724017bc69efdfb012f83f8cf1d17ee4b58a
service:
  main:
    ports:
      main:
        protocol: http
        port: 5231
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SLASH_PORT: "{{ .Values.service.main.ports.main.port }}"
persistence:
  config:
    enabled: true
    mountPath: "/var/opt/slash"
portal:
  open:
    enabled: true
