image:
  pullPolicy: IfNotPresent
  repository: kylemanna/bitcoind
  tag: latest@sha256:ab9b21131e0b2bec720dde4510186f8807685425213927b64a033b77f3e320ad
persistence:
  blockhainstorage:
    enabled: true
    mountPath: /bitcoin/.bitcoin
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8332
        protocol: tcp
        targetPort: 8332
  port2:
    enabled: true
    ports:
      port2:
        enabled: true
        port: 8333
        protocol: tcp
        targetPort: 8333
