image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: necesse@sha256:9b4ebe8f31bb5567fa54025fe36a79f3a1a3b9c32b6bf829cea57fe7b05ea681
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 9023
        protocol: http
        targetPort: 8080
  udpgameport:
    enabled: true
    ports:
      udpgameport:
        enabled: true
        port: 14159
        protocol: udp
        targetPort: 14159
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "1169370"
            GAME_PARAMS: ""
            WORLD_NAME: World
