image:
  repository: ghcr.io/linuxserver/resilio-sync
  tag: 2.8.1@sha256:1fccce4ac6926633aa68b2bc71cf0bbb6a28ee629fb98b8bac55f94438f9382b
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8888
        targetPort: 8888
  bt-tcp:
    enabled: true
    ports:
      bt-tcp:
        enabled: true
        port: 55555
        targetPort: 55555
  bt-udp:
    enabled: true
    ports:
      bt-udp:
        enabled: true
        port: 55555
        targetPort: 55555
        protocol: udp
persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/sync"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
              port: "{{ .Values.service.main.ports.main.targetPort }}"
            readiness:
              type: tcp
              port: "{{ .Values.service.main.ports.main.targetPort }}"
            startup:
              type: tcp
              port: "{{ .Values.service.main.ports.main.targetPort }}"
