image:
  pullPolicy: IfNotPresent
  repository: kasmweb/workspaces
  tag: 1.15.1@sha256:65a84eb389ef2a63055b39648fe0606299d26da6c297b62f5a267268d0db1f3e
kasm:
  mountUdev: false
  mountInput: false
service:
  main:
    ports:
      main:
        port: 10350
        protocol: https
  admin:
    enabled: true
    ports:
      admin:
        enabled: true
        port: 10351
        protocol: https
        targetPort: 3000
persistence:
  data:
    enabled: true
    mountPath: /opt
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    privileged: true
    runAsGroup: 0
    runAsUser: 0
    fsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: https
              path: /
              port: "{{ .Values.service.admin.ports.admin.targetPort }}"
            readiness:
              type: https
              path: /
              port: "{{ .Values.service.admin.ports.admin.targetPort }}"
            startup:
              type: https
              path: /
              port: "{{ .Values.service.admin.ports.admin.targetPort }}"
          env:
            KASM_PORT: "{{ .Values.service.main.ports.main.port }}"
            DOCKER_HUB_PASSWORD: ""
            DOCKER_HUB_USERNAME: ""
