image:
  repository: ghcr.io/static-web-server/static-web-server
  pullPolicy: IfNotPresent
  tag: 2.32.2@sha256:7aff682d27d8dba1e2393a5a8ff46d67df27ff6383bb0eca3615f4a2a9ab3083
service:
  main:
    ports:
      main:
        protocol: http
        port: 38080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            SERVER_ROOT: "/public"
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
persistence:
  config:
    enabled: true
    mountPath: "/public"
portal:
  open:
    enabled: true
