annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/SCALE-support: "false"
  truecharts.org/category: CSI
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: system
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 24.1.6
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: csi-driver-nfs
    version: v4.7.0
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/
    condition: ""
    alias: csi-driver-nfs
    tags: []
    import-values: []
deprecated: false
description: csi-driver-nfs is a nfs CSI driver for kubernetes
home: https://truecharts.org/charts/system/csi-driver-nfs
icon: https://truecharts.org/img/hotlink-ok/chart-icons/csi-driver-nfs.webp
keywords:
  - csi-driver-nfs
  - backup
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: csi-driver-nfs
sources:
  - https://cert-manager.io/
  - https://github.com/cert-manager
  - https://github.com/truecharts/charts/tree/master/charts/system/csi-driver-nfs
  - https://github.com/truecharts/containers/tree/master/apps/alpine
type: application
version: 5.1.1
