image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: citadelfwf@sha256:6d2f614637a8ba58b6062c02377ed9c568964db955d90533a71a16ae0e6fc5b5
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 7777
        protocol: udp
        targetPort: 7777
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 27015
        protocol: udp
        targetPort: 27015
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "489650 "
            GAME_PARAMS: ""
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
