image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/sethforprivacy/simple-monerod
  tag: v0.18.3.3@sha256:36f3ea32c40a285a554f5e761710263330847e2e5f6ce53b2e6b04b4896354af

monero:
  rpcbindip: "0.0.0.0"
  rpcbindport: "18089"
  publicnode: true
  noigd: true
  enablednsblocklist: true
  pruneblockchain: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 18080
        protocol: tcp
        targetPort: 18080
  rpc:
    enabled: true
    ports:
      rpc:
        enabled: true
        port: 18089
        protocol: tcp
        targetPort: 18089

persistence:
  blockchainstorage:
    enabled: true
    mountPath: /home/monero/.bitmonero

portal:
  open:
    enabled: true
