image:
  pullPolicy: IfNotPresent
  repository: webpsh/webps
  tag: latest@sha256:bbb94e7dc0b2d1afcee89507decc6168d5526f394df93280e3060c7c88476a93
persistence:
  storagecache:
    enabled: true
    mountPath: /opt/exhaust
  storagepics:
    enabled: true
    mountPath: /opt/pics
    readOnly: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3333
        protocol: tcp
        targetPort: 3333
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ALLOWED_TYPES: jpg,png,jpeg,bmp,gif
            ENABLE_AVIF: "false"
            QUALITY: "80"
