image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: craftopia@sha256:293d44614a94b3970a75618132bf1fa67eb27d107a4a9a5199e790b726668531
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8787
        protocol: tcp
        targetPort: 8787
  udpgameport:
    enabled: true
    ports:
      udpgameport:
        enabled: true
        port: 8787
        protocol: udp
        targetPort: 8787
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "1670340"
            GAME_PARAMS: ""
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
