image:
  repository: discordgsm/discord-game-server-monitor
  pullPolicy: IfNotPresent
  tag: 2.17.0@sha256:8e6a5c96d3496fc0dc556cd95c3e34e0a6440d31999431300d9ab9404fdffcdd
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10230
        protocol: http
gsm:
  # Server Config
  workers: 2
  timeout: 90
  # Bot Config
  app_token: ""
  whitelist_guilds: []
  app_activity_type: 3
  app_activity_name: ""
  app_presence_advertise: false
  task_query_server: 60
  command_query_public: false
  command_query_cooldown: 5
  web_api_enable: false
  postgres_ssl_mode: disable
  # factorio
  factorio_username: ""
  factorio_auth_token: ""
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          envFrom:
            - secretRef:
                name: "gsm-secret"
          command:
            - /bin/sh
            - -c
            - |
              gunicorn \
              --bind 0.0.0.0:{{ .Values.service.main.ports.main.port }} \
              --workers={{ .Values.gsm.workers }} \
              --worker-class=gthread app:app \
              --timeout {{ .Values.gsm.timeout }} & \
              python -u main.py
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /app/data
cnpg:
  main:
    enabled: true
    database: discord_gsm
    user: discord_gsm
portal:
  open:
    enabled: true
