image:
  pullPolicy: IfNotPresent
  repository: plexripper/plexripper
  tag: v0.20.0@sha256:93697067b7e6c3db015a1bd4ad9a46ab073d8ac98da71d883dee2e7867c4a546
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 7000
        port: 7000
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              type: http
            readiness:
              enabled: true
              type: http
            startup:
              enabled: true
              type: http
persistence:
  config:
    enabled: true
    mountPath: /Config
  downloads:
    enabled: true
    mountPath: /Downloads
portal:
  open:
    enabled: true
