image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/duplicacy
  tag: release-1.7.2@sha256:34e769111534da37f3e6273e5915ff86cee9bd75fbe573ac0b5aeca6e12e5d87
securityContext:
  container:
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 3875
        protocol: http
        targetPort: 3875
persistence:
  config:
    enabled: true
    mountPath: /config
  cache:
    enabled: true
    mountPath: /cache
  logs:
    enabled: true
    mountPath: /logs
portal:
  open:
    enabled: true
