image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: cstrikeczero@sha256:e47fa031b7b8a55e0836db91d057b1ce266b5c71b101f9caae8efc92f363606a
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  tcprcon:
    enabled: true
    ports:
      tcprcon:
        enabled: true
        port: 27015
        protocol: tcp
        targetPort: 27015
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: 90 +app_set_config '90 mod dmc'
            GAME_MOD: 90 mod czero
            GAME_NAME: czero
            GAME_PARAMS: -secure +maxplayers 32 +map as_oilrig
            GAME_PORT: "27015"
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
            readiness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
            startup:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
