image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: vrising@sha256:a4e8d60e8bf64ee5651fe49dba26c2cc58210956a053120369ab86c747b66a80
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 9876
        protocol: udp
        targetPort: 9876
  query:
    enabled: true
    ports:
      query:
        enabled: true
        port: 9877
        protocol: udp
        targetPort: 9877
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ENABLE_BEPINEX: ""
            GAME_ID: "1829350"
            GAME_PARAMS: ""
            PASSWRD: ""
            SERVER_NAME: V Rising Docker
            USERNAME: ""
            VALIDATE: "false"
            WORLD_NAME: world1
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
