image:
  repository: difegue/lanraragi
  tag: v.0.9.21@sha256:0fec3422dc32bb8f8d05b859d85e6ea1fec16b29360eaf42c61aef0152dd1d25
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10177
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/home/koyomi/lanraragi/database"
  content:
    enabled: true
    mountPath: "/home/koyomi/lanraragi/content"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LRR_UID: "{{ .Values.securityContext.container.PUID }}"
            LRR_GID: "{{ .Values.securityContext.pod.fsGroup }}"
