image:
  pullPolicy: IfNotPresent
  repository: jsavargas/telethon_downloader
  tag: latest@sha256:2d585438aa0fc8fb99b4b797462d568752321df29d6c4c29de9ff5fcb4a37819
persistence:
  config:
    enabled: true
    mountPath: /config
  pathdownload:
    enabled: true
    mountPath: /download
  pathwatch:
    enabled: true
    mountPath: /watch
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            TG_API_HASH: " "
            TG_API_ID: " "
            TG_AUTHORIZED_USER_ID: " "
            TG_BOT_TOKEN: ""
            TG_PROGRESS_DOWNLOAD: ""
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
