image:
  repository: tccr.io/tccr/whoami
  pullPolicy: IfNotPresent
  tag: v1.10.1@sha256:36d22e4b8a154919b819bd7283531783eca9076972e8fc631649bb7eade770d9

service:
  main:
    ports:
      main:
        port: 8080

args:
  - --port
  - "8080"
