image:
  repository: rhasspy/wyoming-whisper
  pullPolicy: IfNotPresent
  tag: 2.1.0@sha256:d7485aded378780c4bf67d1f6d4950faad5fd5ddbaa2a7ddb5056012560f033e

service:
  main:
    ports:
      main:
        port: 10300
        protocol: tcp
        targetPort: 10300

wyoming_whisper:
  language: en
  model: tiny-int8
  #  custom_model: ""
  beam_size: 1
  initial_prompt: ""

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              port: 10300
              type: tcp
            readiness:
              port: 10300
              type: tcp
            startup:
              port: 10300
              type: tcp

persistence:
  config:
    enabled: true
    mountPath: /data
  cache:
    enabled: true
    mountPath: /.cache/huggingface/hub

portal:
  open:
    enabled: false
