image:
  repository: corentinth/it-tools
  pullPolicy: IfNotPresent
  tag: 2024.5.13-a0bc346@sha256:c191615f23eb6a18b8faca4dba15fc11caefea250ce3a8e29d249757544092eb
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 80
        port: 18082
persistence:
  cache:
    enabled: true
    type: emptyDir
    mountPath: "/var/cache/nginx"
portal:
  open:
    enabled: true
