image:
  pullPolicy: IfNotPresent
  repository: songkong/songkong
  tag: latest@sha256:f04723a16545c3ddf1e3a7572db4c0e0dac5a21121f3d575513c342c2e4eb6b6
persistence:
  music:
    enabled: true
    mountPath: /music
  songkongconfig:
    enabled: true
    mountPath: /songkong
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4567
        protocol: tcp
        targetPort: 4567
