image:
  repository: vabene1111/recipes
  pullPolicy: IfNotPresent
  tag: 1.5.18@sha256:e5f1287a5961d455e2239f3e96f05987cb018749d565342d93dc8ccadd2bfd65
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_ENGINE: django.db.backends.postgresql
            POSTGRES_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            POSTGRES_PORT: 5432
            POSTGRES_USER: "{{ .Values.cnpg.main.user }}"
            POSTGRES_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            POSTGRES_DB: "{{ .Values.cnpg.main.database }}"
            TANDOOR_PORT: "{{ .Values.service.main.ports.main.port }}"
            ALLOWED_HOSTS: "*"
            COMMENT_PREF_DEFAULT: 1
            CSRF_TRUSTED_ORIGINS: ""
            DEBUG: 0
            FRACTION_PREF_DEFAULT: 0
            GUNICORN_MEDIA: 1
            SECRET_KEY:
              secretKeyRef:
                key: SECRET_KEY
                name: recipes-secrets
            SHOPPING_MIN_AUTOSYNC_INTERVAL: 5
            TIMEZONE: "{{ .Values.TZ }}"
service:
  main:
    ports:
      main:
        port: 10029
persistence:
  media:
    enabled: true
    mountPath: /opt/recipes/mediafiles
  static:
    enabled: true
    mountPath: /opt/recipes/staticfiles
    type: emptyDir
cnpg:
  main:
    enabled: true
    user: recipes
    database: recipes
portal:
  open:
    enabled: true
