image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: longvinter@sha256:21a5bd3fa53ec5517006cab3930d0d9d8a671bebc3921a3801306cdb242755a0
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 27016
        protocol: udp
        targetPort: 27016
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_PARAMS: ""
            GAME_PORT: "27016"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
