image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: cstrike1.6@sha256:e65cfad7942e23997cd6df98852ce27399ac880d741b095e4dee40472b63a801
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  tcprcon:
    enabled: true
    ports:
      tcprcon:
        enabled: true
        port: 27015
        protocol: tcp
        targetPort: 27015
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "90"
            GAME_MOD: ""
            GAME_NAME: cstrike
            GAME_PARAMS: +maxplayers 32 +map de_dust
            GAME_PORT: "27015"
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
            readiness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
            startup:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
