image:
  repository: ghcr.io/linuxserver/emulatorjs
  pullPolicy: IfNotPresent
  tag: 1.9.0@sha256:743afabb4f464151507777fcf0b2f780b5e704352d2bd2cca430a476ebb0275e
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10130
  front:
    enabled: true
    ports:
      front:
        enabled: true
        targetPort: 80
        port: 10124
  ipfs:
    enabled: true
    ports:
      ipfs:
        enabled: true
        targetPort: 4001
        port: 10138
ingress:
  front:
    enabled: false
    targetSelector:
      front: front
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
