image:
  repository: ghcr.io/linuxserver/budge
  tag: 0.0.9@sha256:aa2e4ca98a85a66c8663e132a51ca5161faba6771336ebccac7f6dab862a1f29
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10165
        protocol: http
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NODE_ENV: "production"
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
