image:
  repository: docker
  pullPolicy: IfNotPresent
  tag: 27.1.2-dind@sha256:2f1bfc489d160c04e5fc1cbc76d1f425bd914b3f4eb4cd39123d7aa3cd7c5925
hostNetwork: true
securityContext:
  container:
    privileged: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      main:
        port: 2376
        type: https
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              initialDelaySeconds: 30
              type: tcp
            readiness:
              initialDelaySeconds: 30
              type: tcp
            startup:
              initialDelaySeconds: 30
              type: tcp
          env:
            DOCKER_TLS_CERTDIR: /certs
    type: StatefulSet
    replicas: 1
    strategy: RollingUpdate
persistence:
  docker-certs-ca:
    enabled: true
    mountPath: /config
volumeClaimTemplates:
  docker-certs-client:
    enabled: true
    mountPath: /certs/client
  docker:
    enabled: true
    mountPath: /var/lib/docker
portal:
  open:
    enabled: false
