image:
  pullPolicy: IfNotPresent
  repository: sonatype/nexus3
  tag: 3.71.0@sha256:49a891973f7e390174cac44f9923f0518f77ad95bb7c928b8c1eb52e52657544
persistence:
  data:
    enabled: true
    mountPath: /nexus-data
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsGroup: 200
    runAsUser: 200
  pod:
    fsGroup: 200
service:
  main:
    ports:
      main:
        port: 10288
        targetPort: 8081
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            INSTALL4J_ADD_VM_PARAMS:
              -Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m
              -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs
