image:
  repository: docker.io/zerotier/zerotier
  pullPolicy: IfNotPresent
  tag: 1.14.0@sha256:7404ff5e0700d2d76940d842918adcfc1613fc85f1602dc0c23f7f87029d507d
service:
  main:
    ports:
      main:
        protocol: udp
        targetPort: 9993
        port: 10190
persistence:
  config:
    enabled: true
    mountPath: "/var/lib/zerotier-one"
  tun:
    enabled: true
    type: hostPath
    hostPath: /dev/net/tun
    mountPath: /dev/net/tun
    hostPathType: ""
    readOnly: false
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      add:
        - NET_ADMIN
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            ZEROTIER_API_SECRET: ""
            ZEROTIER_IDENTITY_PUBLIC: ""
            ZEROTIER_IDENTITY_SECRET: ""
