image:
  pullPolicy: IfNotPresent
  repository: redislabs/rejson
  tag: latest@sha256:63f236fb36826c023fae2514b22ce3389392ad66be6f731aad6501be7a4d70ca
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 6379
        protocol: tcp
        targetPort: 6379
