image:
  pullPolicy: IfNotPresent
  repository: coderaiser/cloudcmd
  tag: latest@sha256:8da6f1688136de1ddca784d0e6a9c7ea76043c194210abd510636561530dc912
persistence:
  appdata:
    enabled: true
    mountPath: /root
  mountpath:
    enabled: true
    mountPath: /UNRAID
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8765
        protocol: tcp
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOME: /root
