image:
  repository: thomst08/requestrr
  pullPolicy: IfNotPresent
  tag: v2.1.6@sha256:9d9d64d3cc33b79210c543c60f6b9b20824df00303e53954b4133372dc787ab8

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 4545
        port: 4545

persistence:
  config:
    enabled: true
    mountPath: "/root/config"
  varrun:
    enabled: true

portal:
  open:
    enabled: true
