image:
  repository: josh5/steam-headless
  tag: latest@sha256:308a6d713b3ac3e2e8a9a5d84c826b1268a725259f3938495efbe179a20b64f4
  pullPolicy: IfNotPresent

securityContext:
  container:
    privileged: true
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            PORT_NOVNC_WEB: "{{ .Values.service.main.ports.main.port }}"
            MODE: "primary"
            # MODE = secondary
            # DISPLAY: :0
            # HOST_DBUS: true
            WEB_UI_MODE: "vnc"
            ENABLE_VNC_AUDIO: false
            # NEKO_NAT1TO1: "" needs to be the ip of the host
            ENABLE_SUNSHINE: false
            # SUNSHINE_USER: ""
            # SUNSHINE_PASS: ""
            # USER_PASSWORD: ""
            ENABLE_EVDEV_INPUTS: false

service:
  main:
    ports:
      main:
        protocol: http
        port: 8083

persistence:
  home:
    enabled: true
    mountPath: /home/default
  games:
    enabled: true
    mountPath: /mnt/games
  flatpak:
    enabled: true
    mountPath: /var/lib/flatpak

portal:
  open:
    enabled: true
