annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: operators
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: system
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 24.1.6
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: gpu-operator
    version: v24.3.0
    repository: https://helm.ngc.nvidia.com/nvidia
    condition: ""
    alias: gpu-operator
    tags: []
    import-values: []
deprecated: false
description: Nvidia GPU usage operator
home: https://truecharts.org/charts/system/nvidia-gpu-operator
icon: https://truecharts.org/img/hotlink-ok/chart-icons/nvidia-gpu-operator.webp
keywords:
  - nvidia-gpu-operator
  - loadbalancer
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: nvidia-gpu-operator
sources:
  - https://github.com/nvidia-gpu-operator/nvidia-gpu-operator
  - https://github.com/truecharts/charts/tree/master/charts/system/nvidia-gpu-operator
  - https://github.com/truecharts/containers/tree/master/apps/alpine
  - https://nvidia-gpu-operator.universe.tf
type: application
version: 0.0.1
