image:
  pullPolicy: IfNotPresent
  repository: sourcegraph/server
  tag: 5.6.185@sha256:c6e5ebb1303105ee3b9b85553482b6fa974f96fe3b229d2dfb2535d055c6816c
persistence:
  applicationdatastoragepath:
    enabled: true
    mountPath: /var/opt/sourcegraph
  configstoragepath:
    enabled: true
    mountPath: /etc/sourcegraph
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  adminconsolepo:
    enabled: true
    ports:
      adminconsolepo:
        enabled: true
        port: 2633
        protocol: tcp
        targetPort: 2633
  grafanaport:
    enabled: true
    ports:
      grafanaport:
        enabled: true
        port: 3370
        protocol: tcp
        targetPort: 3370
  main:
    ports:
      main:
        port: 7080
        protocol: http
        targetPort: 7080
