image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/pyload-ng
  tag: latest@sha256:c6ce9438297bb241054f37630ea477c39b446f70ecaf3f1bc9c5bb477fc532e5
persistence:
  config:
    enabled: true
    mountPath: /config
  pathdownloads:
    enabled: true
    mountPath: /downloads
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8000
        protocol: http
        targetPort: 8000
  port9666:
    enabled: true
    ports:
      port9666:
        enabled: true
        port: 9666
        protocol: tcp
        targetPort: 9666
workload:
  main:
    podSpec:
      containers:
        main:
          env:
