image:
  pullPolicy: IfNotPresent
  repository: phasecorex/red-discordbot
  tag: full@sha256:bfc285f86f9abfa188e7675752e7e9b8c09cef744cac610139580622334b9d39
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PREFIX: ""
            TOKEN: ""
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
