image:
  pullPolicy: IfNotPresent
  repository: rocker/rstudio
  tag: 4.4.1@sha256:ee7c4efa46f0b5d46e051393ef05f262aceb959463b15fc3648955965290d231
persistence:
  config:
    enabled: true
    mountPath: /home/rstudio/.config/rstudio
  workspace:
    enabled: true
    mountPath: /home/rstudio/workspace
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8787
        protocol: http
        targetPort: 8787
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DISABLE_AUTH: "false"
            GROUPID: "{{ .Values.securityContext.pod.fsGroup }}"
            PASSWORD: rstudio
            ROOT: "FALSE"
            USER: rstudio
            USERID: "{{ .Values.securityContext.container.runAsUser }}"
