image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/bakito/adguardhome-sync
  tag: v0.6.12@sha256:a604e637a1f95e85c2c4cb817e727e4d4e3dfcd06f1d2623391bb909d25c48d9
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 8080
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - run
          env:
            CRON: "*/10 * * * *"
            FEATURES_CLIENT_SETTINGS: true
            FEATURES_DHCP_SERVER_CONFIG: true
            FEATURES_DHCP_STATIC_LEASES: true
            FEATURES_DNS_ACCESS_LISTS: true
            FEATURES_DNS_REWRITES: true
            FEATURES_DNS_SERVER_CONFIG: true
            FEATURES_FILTERS: true
            FEATURES_GENERAL_SETTINGS: true
            FEATURES_QUERY_LOG_CONFIG: true
            FEATURES_SERVICES: true
            FEATURES_STATS_CONFIG: true
            ORIGIN_PASSWORD: password
            ORIGIN_URL: https://192.168.1.2:3000
            ORIGIN_USERNAME: username
            REPLICA_AUTO_SETUP: false
            REPLICA_INTERFACE_NAME: ""
            REPLICA_PASSWORD: password
            REPLICA_URL: http://192.168.1.3
            REPLICA_USERNAME: username
            RUN_ON_START: true
