image:
  repository: thelounge/thelounge
  pullPolicy: IfNotPresent
  tag: 4.4.3@sha256:89890b06499c69ba8d4afe5de209f628f80dcff31b265c39075b569466366844
service:
  main:
    ports:
      main:
        port: 10061
        targetPort: 9000
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            THELOUNGE_HOME: "/config"
