annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: operators
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: system
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 24.1.6
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: spegel
    version: v0.0.23
    repository: oci://ghcr.io/spegel-org/helm-charts
    condition: ""
    alias: spegel
    tags: []
    import-values: []
deprecated: false
description: A distributed image store
home: https://truecharts.org/charts/system/spegel
icon: https://truecharts.org/img/hotlink-ok/chart-icons/spegel.webp
keywords:
  - spegel
  - loadbalancer
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: spegel
sources:
  - https://github.com/spegel/spegel
  - https://github.com/truecharts/charts/tree/master/charts/system/spegel
  - https://github.com/truecharts/containers/tree/master/apps/alpine
  - https://spegel.universe.tf
type: application
version: 0.0.1
