image:
  repository: ghcr.io/linuxserver/webgrabplus
  pullPolicy: IfNotPresent
  tag: 5.2.2@sha256:2831761a7ff08b1fbe25dd5c4bb5282010087e429ded684c3a6817df56e56086
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: false
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
