image:
  repository: mtlynch/picoshare
  tag: 1.4.4@sha256:36eda700181a517bc8d32f630416ed751fd78c2805a270ff23e85190ecef817c
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10209
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            # web admin password
            PS_SHARED_SECRET: "somesecretcode"
            # optional
            LITESTREAM_BUCKET: ""
            LITESTREAM_ENDPOINT: ""
            LITESTREAM_ACCESS_KEY_ID: ""
            LITESTREAM_SECRET_ACCESS_KEY: ""
            LITESTREAM_RETENTION: 72h
persistence:
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
