image:
  repository: ghcr.io/sbondco/watcharr
  tag: v1.41.0@sha256:2229366989b906418c17df5a54c0c6d378f6044f45c591bba81a6cdd25e30a96
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 3080
        port: 10684

watcharr:
  mode: prod
  jellyfin_host: ""
  signup_enabled: true
  tmdb_key: ""
  debug: false

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            JELLYFIN_HOST: "{{ .Values.watcharr.jellyfin_host }}"
            SIGNUP_ENABLED: "{{ .Values.watcharr.signup_enabled }}"
            TMDB_KEY: "{{ .Values.watcharr.tmdb_key }}"
            DEBUG: "{{ .Values.watcharr.debug }}"
            MODE: "{{ .Values.watcharr.mode }}"
            JWT_SECRET:
              secretKeyRef:
                name: watcharr-secrets
                key: JWT_SECRET

persistence:
  data:
    enabled: true
    mountPath: "/data"

portal:
  open:
    enabled: true
