image:
  pullPolicy: IfNotPresent
  repository: tsightler/ring-mqtt
  tag: 5.7.0@sha256:5a1afcbf819a3f5045aafe895e29bc59e65cfc59fa396f578f884f8cbd115cc2
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 55123
        port: 55123
  rtsp:
    enabled: true
    ports:
      rtsp:
        enabled: true
        protocol: tcp
        targetPort: 8554
        port: 8554
ring:
  mqtt_url: "mqtt://localhost:1883"
  mqtt_options: ""
  livestream_user: ""
  livestream_pass: ""
  disarm_code: ""
  enable_cameras: true
  enable_modes: false
  enable_panic: false
  hass_topic: "homeassistant/status"
  ring_topic: "ring"
  location_ids": []
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
persistence:
  data:
    enabled: true
    mountPath: /data
  ring-config:
    enabled: true
    type: configmap
    objectName: ring-config
    targetSelector:
      main:
        main:
          mountPath: /data/config.json
          subPath: config.json
          readOnly: true
portal:
  open:
    enabled: false
