image:
  pullPolicy: IfNotPresent
  repository: ich777/terrariaserver
  tag: tshock@sha256:c46cfddabcd62db9a7934eb74385e7d147fe9c54e585bf4b502265dee8f376a1
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 9014
        protocol: http
        targetPort: 8080
  tcp:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 7777
terraria:
  autocreate: "1"
  easy_game_params:
    noupnp: true
    secure: false
    steam: false
  game_params: []
  lang: en-US
  maxplayers: 16
  pass: secretpass
  seed: AwesomeSeed
  worldname: scale terraria
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - secretRef:
                name: terraria-secret
