image:
  pullPolicy: IfNotPresent
  repository: accetto/ubuntu-vnc-xfce-firefox-g3
  tag: latest@sha256:8013905c70bef2b297e5d0c4b7f9886700b010c4b50c7eb51bf81411327b9c5e
persistence:
  internalshare:
    enabled: true
    mountPath: /UNRAID_SHARE
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 6901
        protocol: http
        targetPort: 6901
  webuivnc:
    enabled: true
    ports:
      webuivnc:
        enabled: true
        port: 5901
        protocol: tcp
        targetPort: 5901
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            VNC_PW: unraid
            VNC_RESOLUTION: 1360x768
