image:
  pullPolicy: IfNotPresent
  repository: yacy/yacy_search_server
  tag: latest@sha256:ea07f6e515d55097375dc2b3f9a8a38c7b0ec975d177418c29141930a5a124ef
persistence:
  appdata:
    enabled: true
    mountPath: /opt/yacy_search_server/DATA
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  https:
    enabled: true
    ports:
      https:
        enabled: true
        port: 8443
        protocol: tcp
        targetPort: 8443
  main:
    ports:
      main:
        port: 8090
        protocol: http
        targetPort: 8090
