image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: chivalrymw@sha256:1e3ee54e9359fb2b0d911f986779ee4f52fef1831e96940c35a7f772d40e5b65
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  gamequeryport:
    enabled: true
    ports:
      gamequeryport:
        enabled: true
        port: 7010
        protocol: udp
        targetPort: 7010
  main:
    ports:
      main:
        port: 7000
        protocol: udp
        targetPort: 7000
  steamqueryport:
    enabled: true
    ports:
      steamqueryport:
        enabled: true
        port: 27015
        protocol: udp
        targetPort: 27015
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ADMIN_PWD: adminDocker
            GAME_ID: "220070"
            GAME_PARAMS: ?port=7000?queryport=7010
            GAME_PARAMS_EXTRA: -seekfreeloadingserver
            MAP: aocffa-moor_p
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "true"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
