image:
  repository: ghostfolio/ghostfolio
  pullPolicy: IfNotPresent
  tag: 2.103.0@sha256:37d155f903375acba3e4fc739a95bf7dc199bbc86f6f34921b9add4f4c0facf8
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 3333
        targetPort: 3333
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/"
              type: http
            readiness:
              path: "/"
              type: http
            startup:
              type: tcp
          env:
            ALPHA_VANTAGE_API_KEY: ""
            ACCESS_TOKEN_SALT:
              secretKeyRef:
                name: ghostfolio-secrets
                key: ACCESS_TOKEN_SALT
            JWT_SECRET_KEY:
              secretKeyRef:
                name: ghostfolio-secrets
                key: JWT_SECRET_KEY
            DATABASE_URL:
              secretKeyRef:
                name: ghostfolio-secrets
                key: DATABASE_URL
            REDIS_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: plainhost
            REDIS_PASSWORD: "{{ .Values.redis.password }}"
            REDIS_PORT: "6379"
cnpg:
  main:
    enabled: true
    user: ghostfolio
    database: ghostfolio
redis:
  enabled: true
  includeCommon: true
portal:
  open:
    enabled: true
