image:
  repository: ghcr.io/tasmoadmin/tasmoadmin
  tag: v4.1.2@sha256:e158f99d705857756e318c8a10866833355d8648caeb00817550c228313d904b
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            TASMO_DEBUG: 1

service:
  main:
    ports:
      main:
        port: 9541
        protocol: http
        targetPort: 80

persistence:
  data:
    enabled: true
    mountPath: /data

portal:
  open:
    enabled: true
