image:
  pullPolicy: IfNotPresent
  repository: farmos/farmos
  tag: latest@sha256:56f8387fa91816532d858e564205cac258416466dd4a2f949fb4ba3cf255ab95
persistence:
  sitesdirectory:
    enabled: true
    mountPath: /var/www/html/sites
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 80
        protocol: tcp
        targetPort: 80
