image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: memoriesofmars@sha256:d1af332f2a74e0e19ab854adcd6cc9d9e732afd21e14696d253b4c766de7e8f1
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  beaconport:
    enabled: true
    ports:
      beaconport:
        enabled: true
        port: 15000
        protocol: udp
        targetPort: 15000
  main:
    ports:
      main:
        port: 7777
        protocol: udp
        targetPort: 7777
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "897590"
            GAME_PARAMS: ""
            MULTIHOME: ""
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
