image:
  pullPolicy: IfNotPresent
  repository: jasongdove/ersatztv
  tag: v0.8.7@sha256:f33b512c3d33bc4937d355b8a59fbe915f74f4c37ac8e4e879b2fa58cade7421
imageSelector: image
nvidiaImage:
  pullPolicy: Always
  repository: jasongdove/ersatztv
  tag: v0.8.7-nvidia@sha256:c93240ccc5b6b0c567feef47df3381944eaec7312e6d3b82bc066f9608bb1602
persistence:
  config:
    enabled: true
    mountPath: /root/.local/share/ersatztv
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10607
        protocol: http
        targetPort: 8409
vaapiImage:
  pullPolicy: Always
  repository: jasongdove/ersatztv
  tag: v0.8.7-vaapi@sha256:e048d80bea0e456ac66c20c9563b86f552e175717aa336478fcb030499a155f2
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
