image:
  pullPolicy: IfNotPresent
  repository: universalmediaserver/ums
  tag: latest@sha256:b4762953673dcb8726a62eca8430b74b6af25c129c9643d61c44f10dbeef346e
persistence:
  config:
    enabled: true
    mountPath: /root/.config/UMS/
  media:
    enabled: true
    mountPath: /media
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  api:
    enabled: true
    ports:
      api:
        enabled: true
        port: 5001
        protocol: tcp
        targetPort: 5001
  main:
    ports:
      main:
        port: 9001
        protocol: http
        targetPort: 9001
  sub:
    enabled: true
    ports:
      sub:
        enabled: true
        port: 1044
        protocol: tcp
        targetPort: 1044
