image:
  repository: docker.io/gangefors/airdcpp-webclient
  pullPolicy: IfNotPresent
  tag: 2.12.2@sha256:4818da986ca406a13e3451109eef8e9c128f3067595d33bcd930aa2fa51c09a6
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
              path: /
            readiness:
              type: tcp
              path: /
            startup:
              type: tcp
              path: /
          env: {}
service:
  main:
    ports:
      main:
        protocol: tcp
        port: 10155
        targetPort: 5600
  unencrypted-tcp:
    enabled: true
    ports:
      unencrypted-tcp:
        enabled: true
        protocol: tcp
        port: 21248
        targetPort: 21248
  encrypted-tcp:
    enabled: true
    ports:
      encrypted-tcp:
        enabled: true
        protocol: tcp
        port: 21249
        targetPort: 21249
  search-udp:
    enabled: true
    ports:
      search-udp:
        enabled: true
        protocol: udp
        port: 21248
        targetPort: 21248
persistence:
  config:
    enabled: true
    mountPath: /.airdcpp
portal:
  open:
    enabled: true
