image:
  repository: ghcr.io/linuxserver/grav
  pullPolicy: IfNotPresent
  tag: 1.7.46@sha256:6443e8333bca449e770ccfb77662f4514121175b582246623a4a4472983c50b3
service:
  main:
    ports:
      main:
        port: 10012
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
