image:
  repository: ich777/stun-turn-server
  tag: latest@sha256:a5a3cf07151f87800ac461c7ec6cd704a1df8040b40807e6fd856d35f9833a05
  pullPolicy: IfNotPresent

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 5349
        protocol: tcp
        targetPort: 5349
  udpports:
    enabled: true
    ports:
      udpports:
        enabled: true
        port: 5349
        protocol: udp
        targetPort: 5349

persistence:
  config:
    enabled: true
    mountPath: "/stun-turn"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CA_COUNTRY: ""
            CA_LOCALITY: ""
            CA_ORGANIZATION: ""
            CA_STATE_PROV: ""
            CERT_FILE: cert.pem
            CERT_LENGTH: "2048"
            CERT_VALID_DAYS: "3650"
            CIPHER_LIST: ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384
            CLI_PASSWORD: ""
            DATA_PERM: "770"
            DH_FILE: dhparam.pem
            DH_LENGTH: "2048"
            DISPLAY_SECRETS: "true"
            EXTRA_PARAMS: ""
            LISTENING_IP: 0.0.0.0
            MAX_BPS: "0"
            PORT: "{{ .Values.service.main.ports.main.port }}"
            PRIVKEY_FILE: privkey.pem
            REALM: ""
            SECRET: ""
            TOTAL_QUOTA: "100"

portal:
  open:
    enabled: true
