image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/almarklein/timetagger
  tag: v24.07.1-nonroot@sha256:bfbc2d9a8445529c3d3e16c9be7eb670535f6a53c32b668053a91bcfcd7e8f5b
persistence:
  config:
    enabled: true
    mountPath: /opt/_timetagger
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 1000
    runAsUser: 1000
service:
  main:
    ports:
      main:
        port: 10286
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            TIMETAGGER_BIND: 0.0.0.0:{{ .Values.service.main.ports.main.port }}
