image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/rdesktop
  tag: latest@sha256:b88f4521cc4d9fbb8b77250c0b5ccdc4f44c393f62090de9e68b4d78ef4ef912
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-xfce@sha256:37a16e5464ed7491fd94739dc2c08f3ae378df43b727cb8e2e5fe250cd88eec3
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-xfce@sha256:1be9351750725354950f7550426b775ebeca351a7e10fd460b8bdeb4b3ed3218
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-xfce@sha256:04e295bc377da8e05d2e58b99a649d87b05047ca8e5b14c39d56ab944c07d15c
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-kde@sha256:84556ac0c57b8830ff9bc85a7d2877e0bf53c93300dbf22c6774e5806952eb6d
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-kde@sha256:6ec388cd38998d9ddbd5d1f5dc2bfdb845514d6fb3d18b178d91f629706b2356
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-kde@sha256:b1cc30ab6ca5c3e25c516ebabdde573e910d971eefc5d2c21c2614582a888f18
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-kde@sha256:60d5de5e6bad9a738d2e50a2ef26bbc5979cf9ae90ade068b81566bda8264666
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-mate@sha256:7041704551b40780765563af4f866541ece04d4e8390b41a58e40b9d2ff140c9
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-mate@sha256:ef6d8733774b31a2f1ecb50491045473a4cf4ab346e4dddf403ee1551fb27b04
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-mate@sha256:ad7a2098807b751d08d941a48c7c03ff576fbe85a33a0f48fcdb60248370548b
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-mate@sha256:e5f0caec6f8a2d89721118512c067b9637768f02da37a084ff82e382a345e3c2
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-i3@sha256:8e9e15e8a3501c42752b403b58c3a4860f2a1bad3f6d2cc401a9e6740d180438
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-i3@sha256:d39046512f04ae710c5923350d790b7894f38bb2a82aa83418512f6ad2fd83b9
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-i3@sha256:b763c4fadfb0a9654cba78a3e43997cd7e6aa40834626e71dbbdfa325cf3d1ca
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-i3@sha256:0ef4e39009c968123151259f1554160e91de38df0cb3bff1d9106bb612257cca
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-openbox@sha256:65aff71b01a4004875ba250e266e7e389df44af0fae304ef8ac6215120048157
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-openbox@sha256:ee7197ed04e1d57b03f002c45ec7afefab323b162734bd4b5b96936850292856
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-openbox@sha256:56197684539753e4e4326ccda5a821460c1a959343a658aca644bb1bbf7643b6
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-openbox@sha256:51e5321572c0591f1dd5461b269c7fb899c6d364425cb403d1cca00b88b18487
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-icewm@sha256:229c5062e19708ae95b37be376cb0b8b3e081b56f8422005763973cf3c1886b7
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-icewm@sha256:1dc67d60d0317330b194b0355a29d059b436018ead7bbe79bbc6fc14635456c3
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-icewm@sha256:cde964d41e763bec93ace57da7f2134af8df3b6d5c2cc324705107988386e3af
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-icewm@sha256:3a07928c871a35c9eea7a6593bbd2726776ea55c59da589377434749a9d8ea3e
  pullPolicy: Always
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
service:
  main:
    ports:
      main:
        port: 3389
        protocol: tcp
        targetPort: 3389
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
updated: true
