image:
  repository: onerahmet/openai-whisper-asr-webservice
  pullPolicy: IfNotPresent
  tag: "v1.4.1@sha256:0105a8e87df7420989f1aa23970e0dee5a0d1557d03ea79d15297c36b2601464\r"
gpuImage:
  repository: onerahmet/openai-whisper-asr-webservice
  pullPolicy: IfNotPresent
  tag: "v1.4.1-gpu@sha256:7cb13a796fbca157e3508c14c3f78234aa3bcb9a08d86e7ceb2c912ca911a130\r"
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            ASR_MODEL: tiny
            ASR_ENGINE: faster_whisper
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9000
        port: 19900
persistence:
  pip:
    enabled: true
    mountPath: "/root/.cache/pip"
  poetry:
    enabled: true
    mountPath: "/root/.cache/poetry"
  whisper:
    enabled: true
    mountPath: "/root/.cache/whisper"
portal:
  open:
    enabled: true
updated: true
