image:
  repository: docker.io/iyuucn/iyuuplus
  pullPolicy: IfNotPresent
  tag: latest@sha256:e997fe78e80ae21efd4362319d91d217cd43ddfa5de62fc64bb558fbc1851d40
service:
  main:
    ports:
      main:
        targetPort: 8787
        port: 10188
persistence:
  config:
    enabled: true
    mountPath: "/IYUU/db"
  torrents:
    enabled: true
    mountPath: "/torrents"
  btbackup:
    enabled: true
    mountPath: "/BT_backup"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
