image:
  repository: ghcr.io/atuinsh/atuin
  pullPolicy: IfNotPresent
  tag: 18.3.0@sha256:678def8e9d59652a502759ca431f9c5b54ebdd5e9361507c7fcf24705c9862e0

securityContext:
  container:
    runAsUser: 1000
    runAsGroup: 1000

service:
  main:
    ports:
      main:
        protocol: http
        port: 8888

atuin:
  open_registration: false

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - server
            - start
          env:
            ATUIN_HOST: 0.0.0.0
            ATUIN_PORT: "{{ .Values.service.main.ports.main.port }}"
            ATUIN_OPEN_REGISTRATION: "{{ .Values.atuin.open_registration }}"
            ATUIN_CONFIG_DIR: /config
            ATUIN_DB_URI:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
            ATUIN_DB_USERNAME: "{{ .Values.cnpg.main.user }}"
            ATUIN_DB_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password

persistence:
  config:
    enabled: true
    mountPath: "/config"

cnpg:
  main:
    enabled: true
    user: atuin
    database: atuin

portal:
  open:
    enabled: false
