image:
  repository: stashapp/stash
  tag: v0.26.2@sha256:7e71c17a2ce69305889bb3305b057929066c767037b2415a354f2b7dbeff6013
  pullPolicy: IfNotPresent
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 9999
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            STASH_PORT: "{{ .Values.service.main.ports.main.port }}"
            STASH_STASH: /data
            STASH_GENERATED: /generated
            STASH_METADATA: /metadata
            STASH_CACHE: /cache
persistence:
  config:
    enabled: true
    mountPath: "/root/.stash"
  cache:
    enabled: true
    mountPath: "/cache"
  generated:
    enabled: true
    mountPath: "/generated"
  metadata:
    enabled: true
    mountPath: "/metadata"
  blobs:
    enabled: true
    mountPath: "/blobs"
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
