image:
  repository: ghcr.io/go-shiori/shiori
  pullPolicy: IfNotPresent
  tag: v1.7.0@sha256:85a47b264a5b96dec5e558b385f03cf867397dcc37d36d08b7f035681c846649
service:
  main:
    ports:
      main:
        port: 10098
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SHIORI_DIR: "{{ .Values.persistence.data.mountPath }}"
            SHIORI_DBMS: "postgresql"
            SHIORI_PG_PORT: "5432"
            SHIORI_PG_USER: "{{ .Values.cnpg.main.user }}"
            SHIORI_PG_NAME: "{{ .Values.cnpg.main.database }}"
            SHIORI_PG_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            SHIORI_PG_PASS:
              secretKeyRef:
                name: cnpg-main-user
                key: password
persistence:
  data:
    enabled: true
    mountPath: /data
cnpg:
  main:
    enabled: true
    user: shiori
    password: shiori
portal:
  open:
    enabled: true
