image:
  repository: jlesage/mkvcleaver
  tag: v24.07.1@sha256:88c2569ec61a97a74b06a31c22967555fea32594040bdb2bc7c5eb08420d6c4a
  pullPolicy: IfNotPresent
mkvcleaver:
  KEEP_APP_RUNNING: false
  DISPLAY_WIDTH: 1280
  DISPLAY_HEIGHT: 768
  SECURE_CONNECTION: false
  ENABLE_CJK_FONT: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    capabilities:
      disableS6Caps: true
      add:
        - CHOWN
        - SETGID
        - SETUID
        - FOWNER
        - DAC_OVERRIDE
        - KILL
        - NET_BIND_SERVICE
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            VNC_PASSWORD: ""
          envFrom:
            - configMapRef:
                name: "mkvcleaver"
configmap:
  mkvcleaver:
    enabled: true
    data:
      ENABLE_CJK_FONT: '{{ ternary "1" "0" .Values.mkvcleaver.ENABLE_CJK_FONT }}'
      KEEP_APP_RUNNING: '{{ ternary "1" "0" .Values.mkvcleaver.KEEP_APP_RUNNING }}'
      SECURE_CONNECTION: '{{ ternary "1" "0" .Values.mkvcleaver.SECURE_CONNECTION }}'
      DISPLAY_WIDTH: "{{ .Values.mkvcleaver.DISPLAY_WIDTH }}"
      DISPLAY_HEIGHT: "{{ .Values.mkvcleaver.DISPLAY_HEIGHT }}"
service:
  main:
    ports:
      main:
        type: tcp
        port: 5800
        targetPort: 5800
  vnc:
    enabled: true
    ports:
      vnc:
        enabled: true
        port: 5900
        targetPort: 5900
persistence:
  config:
    enabled: true
    mountPath: "/config"
  storage:
    enabled: true
    mountPath: "/storage"
portal:
  open:
    enabled: true
