image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: assettocorsa@sha256:9b0526736feb1170a5f197c8cfeab2b10a702e0b4f40ff32cdce38d697fe4475
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  assetto:
    enabled: true
    ports:
      assetto:
        enabled: true
        port: 8772
        protocol: tcp
        targetPort: 8772
  main:
    ports:
      main:
        port: 9600
        protocol: tcp
        targetPort: 9600
  stracker:
    enabled: true
    ports:
      stracker:
        enabled: true
        port: 50041
        protocol: tcp
        targetPort: 50041
  tcp2:
    enabled: true
    ports:
      tcp2:
        enabled: true
        port: 8081
        protocol: tcp
        targetPort: 8081
  udp:
    enabled: true
    ports:
      udp:
        enabled: true
        port: 9600
        protocol: udp
        targetPort: 9600
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "302550"
            INSTALL_ASSETTO_SERVER_MANAGER: ""
            INSTALL_STRACKER: ""
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
