image:
  repository: docker.io/nodered/node-red
  pullPolicy: IfNotPresent
  tag: 4.0.2@sha256:f86afc0129a060f73fa2af34e3dffdeb9eaaa6f5620cfc181f63ade86aad4991
service:
  main:
    ports:
      main:
        port: 1880
        targetPort: 1880
persistence:
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
