image:
  repository: feramance/qbitrr
  pullPolicy: IfNotPresent
  tag: v4.8.3@sha256:e95614451913fa44c7d9c4749cddc3ea40d6d627a2f77457e0b7e2f566c96a81
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      initContainers:
        1-create-config-file:
          type: install
          enabled: true
          imageSelector: "image"
          command:
            - /bin/sh
            - -c
          args:
            - |
              conf="/config/config.toml"
              example="https://raw.githubusercontent.com/Feramance/qBitrr/master/config.example.toml"
              if [ -f "$conf" ]; then
                echo "$conf exists. Skipping..."
              else
                echo "$conf does not exist... Downloading the example from upstream..."
                wget "$example" -O $conf || echo "Failed to download"
              fi
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            QBITRR_OVERRIDES_DATA_PATH: /config
persistence:
  config:
    enabled: true
    mountPath: /config
    targetSelector:
      main:
        main: {}
        1-create-config-file: {}
  downloads:
    enabled: true
    mountPath: /completed_downloads
portal:
  open:
    enabled: false
