image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: stn@sha256:1a016feb60d0e31ae654bb71a6e4bb61845466c93c988e8d7c3b392d651c0b4f
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 7950
        protocol: udp
        targetPort: 7950
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DEBUG_OUTPUT: "false"
            GAME_ID: "1502300"
            GAME_PARAMS: ""
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
