image:
  repository: benzino77/tasmocompiler
  tag: latest@sha256:61d513b9989b1ed2ec74a9cc160e2598468baa7e3ca6aea0dd48d77c538a9314
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 14003
        protocol: http
        targetPort: 3000

portal:
  open:
    enabled: true
