image:
  repository: inovector/mixpost
  pullPolicy: IfNotPresent
  tag: v1.7.1@sha256:9b0761473f8f5f79ea0077722070f4268bd5c8c2b9e8b147acc03ec29e3a5d20
service:
  main:
    ports:
      main:
        targetPort: 80
        port: 80
persistence:
  storage:
    enabled: true
    mountPath: "/var/www/html/storage/app"
  logs:
    enabled: true
    mountPath: "/var/www/html/storage/logs"
  varrun:
    enabled: false
mariadb:
  enabled: true
  mariadbUsername: mixpost
  mariadbDatabase: mixpost
redis:
  enabled: true
  redisUsername: default
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            startup:
              type: tcp
            readiness:
              type: tcp
          env:
            DB_DATABASE: "{{ .Values.mariadb.mariadbDatabase }}"
            DB_USERNAME: "{{ .Values.mariadb.mariadbUsername }}"
            DB_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainhost
            DB_PASSWORD:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: mariadb-password
            REDIS_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: plainhost
            REDIS_PASSWORD:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: redis-password
