image:
  repository: ghcr.io/a-sync/game-server-watcher
  pullPolicy: IfNotPresent
  tag: v3.1.16@sha256:1ed4fdf7a195bfcfc16a3bbe2370506da09bcd847266fadfa97d6767d54a2864

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        port: 10690

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            # Writeable folder for data storage
            DATA_PATH: "{{.Values.persistence.data.mountPath }}"
            # Web service host
            HOST: 0.0.0.0
            # Web service port
            PORT: "{{ .Values.service.main.ports.main.port }}"
            # Admin PASSWORD
            SECRET: secret
            # Enable or Disable debug mode
            DBG: 0
            # Game server info refresh interval in minutes
            REFRESH_TIME_MINUTES: 2
            # Steam web API key
            STEAM_WEB_API_KEY: ""
            # Discord bot token
            DISCORD_BOT_TOKEN: ""
            # Telegram bot token
            TELEGRAM_BOT_TOKEN: ""
            # Slack bot token
            SLACK_BOT_TOKEN: ""
            # Slack app token
            SLACK_APP_TOKEN: ""

persistence:
  data:
    enabled: true
    mountPath: "/data"

portal:
  open:
    enabled: true
