image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/kiwix/kiwix-serve
  tag: 3.7.0@sha256:9bd81257180e2d5328df1a139c3af76de453d6f2c475235035645c92054a168f
service:
  main:
    ports:
      main:
        port: 10323
        protocol: http
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DOWNLOAD: http://download.kiwix.org/zim/wikipedia_en_chemistry_nopic.zim
            PORT: "{{ .Values.service.main.ports.main.port }}"
          args:
            - "*.zim"
