image:
  repository: ghcr.io/neggles/sd-webui-docker
  tag: latest@sha256:96f9cddaf08760690b0ab486b86ac36553cbf70185a41c330f3d1965746ee714
  pullPolicy: Always
vladImage:
  repository: ghcr.io/neggles/sd-webui-docker
  tag: vlad@sha256:5fa3b1a94721415c887bc7f8f1b7edd3ab62408a54eb988d242d20e447fca93d
  pullPolicy: Always

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 7860
        targetPort: 7860

# securityContext:
#   runAsUser: 0
#   runAsGroup: 0
#   fsGroup: 0
#   readOnlyRootFilesystem: false

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          args:
            - "--skip-version-check"
          env:
            PYTHONUNBUFFERED: "1"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true

persistence:
  data:
    enabled: true
    mountPath: /data
  output:
    enabled: true
    mountPath: /output

portal:
  open:
    enabled: true
