image:
  repository: shlinkio/shlink-web-client
  pullPolicy: IfNotPresent
  tag: 4.1.2@sha256:bd0dad6321220398fecbc7cfb2eb438c32f466747d7a39e51cccf3747b6f3e03
service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10154
        protocol: http
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SHLINK_SERVER_URL: ""
            SHLINK_SERVER_API_KEY: ""
            SHLINK_SERVER_NAME: ""
