image:
  pullPolicy: IfNotPresent
  repository: mikeah/cura-novnc
  tag: latest@sha256:863dc1d78abd5d27b5c961b8d23ff5948610b02ce5ad04459d617f56fbe7ca69
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 16081
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  homefolder:
    enabled: true
    mountPath: /home/cura/
  prints:
    enabled: true
    mountPath: /prints/
portal:
  open:
    enabled: true
