image:
  repository: vexorian/dizquetv
  pullPolicy: IfNotPresent
  tag: 1.5.3@sha256:4de86b6ceaae002ec67e50040b05d9fbc62c6b64b670959427c43a0e0a85c6b9
nvidiaImage:
  repository: vexorian/dizquetv
  pullPolicy: IfNotPresent
  tag: 1.5.3-nvidia@sha256:13ef8f5edac31c8a916433c8bc9cda02d339f0eb65260dec6b08a9d8888f1eeb

service:
  main:
    ports:
      main:
        port: 10071
        targetPort: 8000

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /

persistence:
  config:
    enabled: true
    mountPath: /home/node/app/.dizquetv

portal:
  open:
    enabled: true
