image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: mordhau@sha256:9226aa12eddbabafe69d0a008d747e8a8cebfd33b48f081bca1a29a92bd8e870
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  beaconport:
    enabled: true
    ports:
      beaconport:
        enabled: true
        port: 15000
        protocol: udp
        targetPort: 15000
  main:
    ports:
      main:
        port: 7777
        protocol: udp
        targetPort: 7777
  udp:
    enabled: true
    ports:
      udp:
        enabled: true
        port: 27015
        protocol: udp
        targetPort: 27015
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BEACON_PORT: "15000"
            GAME_ID: "629800"
            GAME_PARAMS: ""
            GAME_PORT: "7777"
            PASSWRD: ""
            QUERY_PORT: "27015"
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
