image:
  repository: ghcr.io/linuxserver/minetest
  pullPolicy: IfNotPresent
  tag: 5.9.0@sha256:c872b6a10467086d46994a1354b67facc04e5f90051e9313cfc639a5afc7cda4
service:
  main:
    ports:
      main:
        protocol: udp
        targetPort: 30000
        port: 30000
persistence:
  config:
    enabled: true
    mountPath: "/config/.minetest"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
