image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: insurgencysandstorm@sha256:d8ee42f562a0a621691f0a1e89ca213b7da4df7884cfccf2e894d54e648d5fe1
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 27102
        protocol: udp
        targetPort: 27102
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 27131
        protocol: udp
        targetPort: 27131
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "581330"
            GAME_PARAMS: Oilfield?Scenario=Scenario_Refinery_Push_Security?MaxPlayers=28?Password=Docker
            GAME_PORT: "27102"
            PASSWRD: ""
            QUERY_PORT: "27131"
            SERVER_NAME: DockerServer
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
