image:
  pullPolicy: IfNotPresent
  repository: ich777/fluttercoin
  tag: latest@sha256:760ed8215e9aef2e2aa96498da87cbc964b89f4486e337b216fd7c3f26c1b767
persistence:
  datapath:
    enabled: true
    mountPath: /fluttercoin
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  jsonremoteport:
    enabled: true
    ports:
      jsonremoteport:
        enabled: true
        port: 7474
        protocol: tcp
        targetPort: 7474
  main:
    ports:
      main:
        port: 8080
        protocol: http
        targetPort: 8080
  peertopeerconn:
    enabled: true
    ports:
      peertopeerconn:
        enabled: true
        port: 7408
        protocol: tcp
        targetPort: 7408
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CUSTOM_RES_H: "768"
            CUSTOM_RES_W: "1024"
            DATA_PERM: "770"
            EXTRA_PARAMS: -bind=0.0.0.0
