image:
  repository: itzg/mc-router
  pullPolicy: IfNotPresent
  tag: 1.22.0@sha256:7bb8ac0760810bbac43840fcaa616b5e403b1cf5dc3c554aa5eb6df22b3648ee
service:
  main:
    ports:
      main:
        port: 25564
  minecraft:
    enabled: true
    ports:
      minecraft:
        enabled: true
        port: 25565
mcrouter:
  host_minecraft: []
  #  - "minecraft.local=minecraft-java.ix-minecraft-java.svc.cluster.local:25565"
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          envFrom:
            - secretRef:
                name: "secrets"
          env:
            API_BINDING: ":{{ .Values.service.main.ports.main.port }}"
            PORT: "{{ .Values.service.minecraft.ports.minecraft.port }}"
portal:
  open:
    enabled: false
