image:
  repository: jvmilazz0/kavita
  pullPolicy: IfNotPresent
  tag: 0.8.2@sha256:3fbd326ca5bde61318200751289a289ef0040b4c842874814ffaf05107d91fe8
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 5000
        port: 10189
persistence:
  config:
    enabled: true
    mountPath: "/kavita/config"
  manga:
    enabled: true
    mountPath: "/manga"
  tmp:
    enabled: false
portal:
  open:
    enabled: true
