image:
  pullPolicy: IfNotPresent
  repository: petersem/posterr
  tag: latest@sha256:be3f19fde0b0c380f802eb596064fcd100639bf44058a4b1b680fa3773723961
service:
  main:
    ports:
      main:
        port: 9876
        protocol: http
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: /usr/src/app/config
  custom:
    enabled: true
    mountPath: /usr/src/app/public/custom
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
