image:
  repository: linuxserver/snapdrop
  tag: latest@sha256:837ef6946e1abeaa8ca42e843a6c45d986c8625c52fa036fb95765925c703fcd
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10215
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
