image:
  pullPolicy: IfNotPresent
  repository: dlandon/z80pack
  tag: latest@sha256:206d1cbc7d98882dae2c9af38743e408c8f9ea2b4f9a91f72f98464c640b8de5
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4200
        protocol: tcp
        targetPort: 4200
