annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: operators
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: system
apiVersion: v2
appVersion: 0.0.3
dependencies:
  - name: common
    version: 24.1.6
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: kubeapps
    version: 15.3.9
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: ""
    alias: ogkubeapps
    tags: []
    import-values: []
deprecated: false
description: KubeApps is a Kubernetes-as-Apps solution
home: https://truecharts.org/charts/system/kubeapps
icon: https://truecharts.org/img/hotlink-ok/chart-icons/kubeapps.webp
keywords:
  - kubeapps
  - catalog
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: kubeapps
sources:
  - https://cert-manager.io/
  - https://ghcr.io/xstar97/my-proxy-service
  - https://github.com/cert-manager
  - https://github.com/truecharts/charts/tree/master/charts/system/kubeapps
type: application
version: 5.1.1
